import src.OwlControllerPython as owl

m: owl.AirplaneManager = owl.get_airplane_manager()
m.flush()
a: owl.AirplaneController = m.get_airplane("127.0.0.1")
m.start()
a.use_fast_mode()
m.sleep(3)
a.takeoff(150)
m.sleep(5)
a.takeoff(150)
m.sleep(5)
a.forward(200)
m.sleep(5)
a.back(200)
m.sleep(5)
a.right(200)
m.sleep(5)
a.left(200)
m.sleep(5)
a.down(100)
m.sleep(5)
a.up(100)
m.sleep(5)
a.land()
m.destroy()